// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwtkptvsgwffukcogzpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3dGtwdHZzZ3dmZnVrY29nenBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTU1OTYsImV4cCI6MjA2MTI3MTU5Nn0.p6HddwCFGWZqmWRrQSsBzXliDjc3FGZICbccUjNPags";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);